language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install flake8
  - pip install ./
script:
  - flake8 py_ip2location_downloader/
  - py_ip2location_downloader -h